### ISSUE TITLE
Trivial Error in cortx-ha rpm creation in nested directory

### ISSUE THREAD

**Issue by shailesh-vaidya** [Seagate/cortx-ha#230] opened 2020-10-26 13:10 UTC
I observed trivial error while building cortx-ha packages.  If we clone cortx-ha in nested directory of multiple depth the rpm creation failed. We face this issue while creating OS wise nested folder for component build jobs. It's working fine with normal folder structure. So it's not blocking issue.
 
From investigation found that it's failing during Python virtual environment creation in pcswrap compilation phase. Steps to reproduce issue as as below,
 
Create multiple nested directory structure and clone cortx-ha repo
 ```
mkdir -p /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003
git clone https://github.com/Seagate/cortx-ha /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/
 ```
Follow build steps,
 
`./jenkins/build.sh -b 10 `
 
This script error out as,
 ```
+ make -C pcswrap install DESTDIR=/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILDROOT/cortx-ha-1.0.0-10_37b719e.x86_64/opt/seagate/cortx/ha
make: Entering directory `/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILD/cortx/pcswrap'
--> Initializing virtual env in /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILD/cortx/pcswrap/.py3venv
--> Installing pip modules in virtual env
bash: /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILD/cortx/pcswrap/.py3venv/bin/pip3: /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/: bad interpreter: No such file or directory
make: *** [/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILD/cortx/pcswrap/.py3venv] Error 126
make: Leaving directory `/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/BUILD/cortx/pcswrap'
error: Bad exit status from /var/tmp/rpm-tmp.55IHqB (%install)
 
 
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.55IHqB (%install)
 ```

**Comment by cortx-admin** [comment] 2021-09-30 05:41
> Subhash Arya commented in Jira Server:

Not required ( and not reproducible) for R2.

**Comment by hessio** [comment] 2021-11-12 14:19
Hi @shailesh-vaidya what is the status on this issue, I see it is not a problem with R2 now? Does this mean we can close this issue?

**Comment by cortx-admin** [comment] 2022-01-17 15:35
> Akash Dudhane commented in Jira Server:

h3. Tried to reproduce issue on my-setup using steps provided in description:
 # Created multiple nested directory structure and cloned cortx-ha repo
{code:java}
[root@ssc-vm-g4-rhev4-0075 ~]# mkdir -p /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003

[root@ssc-vm-g4-rhev4-0075 ~]# git clone https://github.com/Seagate/cortx-ha /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/
Cloning into '/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003'...
remote: Enumerating objects: 5866, done.
remote: Counting objects: 100% (1270/1270), done.
remote: Compressing objects: 100% (571/571), done.
remote: Total 5866 (delta 852), reused 1002 (delta 696), pack-reused 4596
Receiving objects: 100% (5866/5866), 1.36 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4044/4044), done.

[root@ssc-vm-g4-rhev4-0075 ~]# cd /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003{code}

 # Run build.sh script
{code:java}
[root@ssc-vm-g4-rhev4-0075 centos-7.8.2003]# ./jenkins/build.sh -b 10
.
.
.
.
++ ls -1 /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/
++ grep x86_64
++ grep -v debug
+ rpm_file=cortx-ha-2.0.0-10_d930a30.x86_64.rpm
+ mkdir -p /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/RPMS/x86_64
+ cp /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/cortx-ha-2.0.0-10_d930a30.x86_64.rpm /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/RPMS/x86_64/
+ cd /tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild
+ echo '********** RPM ****************'
********** RPM ****************
++ find -name '*.rpm'
+ realpath ./RPMS/x86_64/cortx-ha-2.0.0-10_d930a30.x86_64.rpm
/tmp/workspace/GitHub-custom-ci-builds/custom_build_test/centos-7.8.2003/dist/rpmbuild/RPMS/x86_64/cortx-ha-2.0.0-10_d930a30.x86_64.rpm
[root@ssc-vm-g4-rhev4-0075 centos-7.8.2003]#{code}

          *rpm created Successfully.*

**Comment by cortx-admin** [comment] 2022-01-18 10:02
> Akash Dudhane commented in Jira Server:

Non reproducible.

**Closed by cortx-admin** 2022-01-18 10:02 UTC
Labels: needs-triage, Community, Status: L1 Triage, Patrick

**Comment by cortx-admin** [comment] 2022-01-27 11:56
> Taizun Kachwala commented in Jira Server:

We tried to reproduce on external network, seems like issue is not reproduced. We could also execute build-script in nested directories without any failure. Hence we consider this as NO REPRO & closing it.

**Comment by cortx-admin** [comment] 2022-01-27 11:56
> Taizun Kachwala commented in Jira Server:

Cannot reproduce
